### ISSUE TITLE
Single click is called even in case of double click

### ISSUE THREAD

**Issue by colesnicov** [GerLech/TouchEvent#2]
Hi. I want to ask. Why is '_onTouchClick' called even if '_onTouchDblClick' is double-clicked on the screen? Could this be prevented? Thank you.

**Comment by GerLech** [comment]
No, since first comes the click event and if a second click event occurs within a certain time, a doubleclick will be generated. But you can delay the reaction on click event and ignore it if also a doubleclick event occurs.
